project:
  type: website
  output-dir: docs
  resources: 
    - "resume/resume.pdf"

website:
  page-navigation: true
  navbar:
    search: true
    background: "#008080"
    tools:
      - icon: github
        menu:
          - text: Source Code
            href:  https://github.com/jennylsmith/jennylsmith.github.io
          - text: Report a Bug
            href:  https://github.com/jennylsmith/jennylsmith.github.io/issues
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Resume"
        id: "Resume"
        href: resume/resume.qmd
      - text: "Projects"
        menu: 
          - text: "select publications"
            href: projects/publications.qmd
          - text: "data visualization"
            href: projects/data_visualization.qmd
  sidebar:
    - id: "Resume"
    - tools:
      - icon: filetype-pdf
        menu:
          - text: "download pdf resume"
            href: resume/resume.pdf
format:
  html:
    theme: 
      - tables.scss
      - lumen
    grid:
      sidebar-width:	175px
      body-width:	900px
      margin-width:	200px
      gutter-width:	1em
    toc: true
    toc-depth: 3
    link-external-newwindow: true


