project:
  type: website
  output-dir: docs
  resources: 
    - "resume/jlsmith_resume.pdf"

website:
  page-navigation: true
  navbar:
    search: true
    background: "#008080"
    tools:
      - icon: github
        menu:
          - text: Source Code
            href:  https://github.com/jennylsmith/jennylsmith.github.io
          - text: Report a Bug
            href:  https://github.com/jennylsmith/jennylsmith.github.io/issues
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Resume"
        id: "Resume"
        href: resume/resume.qmd
      - text: "Projects"
        menu: 
          - text: "Data visualization"
            href: projects/data_visualization.qmd
          - text: "Genomics pipelines and tools"
            href: projects/genomics_applications_pipelines.qmd
          - text: "Select publications"
            href: projects/publications.qmd
  # sidebar:
  #   - text: "Resume"
  #     id: "Resume"
  #   - tools:
  #     - icon: filetype-pdf
  #       menu:
  #         - text: resume pdf
  #           href: resume/jlsmith_resume.pdf
format:
  html:
    theme: 
      - custom.scss
      - lumen
    grid:
      sidebar-width:	150px
      body-width:	875px
      margin-width:	200px
      gutter-width:	1em
    toc: true
    toc-depth: 3
    link-external-newwindow: true


