project:
  type: website

website:
  page-navigation: true
  navbar:
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "Resume"
        href: resume.qmd
      - text: "Projects"
        menu: 
          - projects/publications.qmd
          - projects/data_visualization.qmd
    tools:
      - icon: github
        menu:
          - text: Source Code
            href:  https://github.com/jennylsmith/jennylsmith.github.io
          - text: Report a Bug
            href:  https://github.com/jennylsmith/jennylsmith.github.io/issues
            
format:
  html:
    theme: 
      - tables.scss
      - darkly
    toc: true


